services:
  - type: web
    name: coleccionable-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn coleccionable_API.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: MONGODB_DB_NAME
        value: tienda_coleccionables
